/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Hospital;

import Doctor.Doctor;
import GPAppointment.GPAppointment;
import Login.Login;
import Patient.Patient;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author paul.oamen
 */
public class Hospital extends javax.swing.JFrame {
private JFrame frame;
    /**
     * Creates new form Hospital
     */
    public Hospital() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnUpdate = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jbtnDoctor = new javax.swing.JButton();
        jbtnPayment = new javax.swing.JButton();
        jbtnPharmacyOffice = new javax.swing.JButton();
        jbtnPrint = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnPatient = new javax.swing.JButton();
        jbtnGPAppointment = new javax.swing.JButton();
        jbtnLogin = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtxtPrescription = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jtxtRef = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jtxtDose = new javax.swing.JTextField();
        jtxtNumberTablets = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtLot = new javax.swing.JTextField();
        jtxtIssuedDate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtExpDate = new javax.swing.JTextField();
        jtxtDailyDose = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtxtPossibleSideEffects = new javax.swing.JTextField();
        jtxtFurtherInformation = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtxtStorageAdvice = new javax.swing.JTextField();
        jtxtAdministration = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtxtDrivingUsingMachines = new javax.swing.JTextField();
        jtxtHowtoUseMedication = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jtxtPatientID = new javax.swing.JTextField();
        jtxtDoctorNHSNo = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jcmbNameTablets = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jtxtPatientName = new javax.swing.JTextField();
        jtxtAddress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1400, 800));
        setPreferredSize(new java.awt.Dimension(1400, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnUpdate.setText("Update");
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 30));

        jbtnDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnDelete.setText("Delete");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 140, 30));

        jbtnDoctor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnDoctor.setText("Doctor");
        jbtnDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDoctorActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 140, 30));

        jbtnPayment.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnPayment.setText("Reset");
        jbtnPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPaymentActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, 110, 30));

        jbtnPharmacyOffice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnPharmacyOffice.setText(" Prescription");
        jbtnPharmacyOffice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPharmacyOfficeActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnPharmacyOffice, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 150, 30));

        jbtnPrint.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnPrint.setText("Print");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 10, 120, 30));

        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 10, 110, 30));

        jbtnPatient.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnPatient.setText("Patient");
        jbtnPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPatientActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 140, 30));

        jbtnGPAppointment.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnGPAppointment.setText("GP Appointment");
        jbtnGPAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGPAppointmentActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnGPAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 150, 30));

        jbtnLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnLogin.setText("Login");
        jbtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 10, 100, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 1330, 60));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtPrescription.setBackground(new java.awt.Color(204, 255, 255));
        jtxtPrescription.setColumns(20);
        jtxtPrescription.setLineWrap(true);
        jtxtPrescription.setRows(5);
        jScrollPane3.setViewportView(jtxtPrescription);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 390, 420));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 90, 410, 440));

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Patient Prescription");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 380, 60));

        jPanel4.setBackground(new java.awt.Color(51, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Hospital Management Systems");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1330, 80));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel2.setText("Hospital Management Systems");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("Reference No.");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jtxtRef.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 210, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setText("Name of Tablets:");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setText("Dose (mg):");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jtxtDose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 210, -1));

        jtxtNumberTablets.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtNumberTablets, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 210, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Number of Tablets:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jtxtLot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtLot, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 210, -1));

        jtxtIssuedDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtIssuedDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 210, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Issued Date:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Exp Date:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        jtxtExpDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtExpDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 210, -1));

        jtxtDailyDose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtDailyDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 210, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Daily Dose:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        jtxtPossibleSideEffects.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtPossibleSideEffects, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, 210, -1));

        jtxtFurtherInformation.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtFurtherInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 170, 210, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Further Information:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Storage Advice:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, -1, -1));

        jtxtStorageAdvice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtStorageAdvice, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 210, 210, -1));

        jtxtAdministration.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtAdministration, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 450, 210, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Date of Birth:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Driving and Using Machines:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, -1, -1));

        jtxtDrivingUsingMachines.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtDrivingUsingMachines, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 250, 210, -1));

        jtxtHowtoUseMedication.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtHowtoUseMedication, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 290, 210, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("How to Use Medication:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, -1, -1));

        jtxtPatientID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtPatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 330, 210, -1));

        jtxtDoctorNHSNo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtDoctorNHSNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 370, 210, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("NHS Number:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, -1, -1));

        jcmbNameTablets.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcmbNameTablets.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Make a Selection", "Ibuprofen", "Co-codamol", "Paracetamol", "Amlodipine" }));
        jcmbNameTablets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbNameTabletsActionPerformed(evt);
            }
        });
        getContentPane().add(jcmbNameTablets, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 210, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Possible Side Effects:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Patient ID:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Patient Address:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("Patient Name:");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, -1, -1));

        jtxtPatientName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 410, 210, -1));

        jtxtAddress.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 490, 210, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("LOT:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name of Tablets", "Reference No.", "Dose (mg)", "Number of Tablets", "LOT", "Issued Date", "Exp Date", "Daily Dose", "Possible Side Effects", "Further Information", "Storage Advice", "Administration", "Driving and Using Machine", "How to Use Medication", "Patient ID", "Doctor NHS No.", "Date of Birth:", "Patient Address"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, 1350, 160));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jcmbNameTabletsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbNameTabletsActionPerformed
        if (jcmbNameTablets.getSelectedItem().equals("Ibuprofen"))
        {
            jtxtRef.setText("Ibu8568959");
            jtxtDose.setText("2");
            jtxtNumberTablets.setText("32");
            jtxtLot.setText("561005875");
            jtxtIssuedDate.setText("06/05/2018");
            jtxtExpDate.setText("04/05/2019");
            jtxtDailyDose.setText("4");

            jtxtPossibleSideEffects.setText("Bleeding");
            jtxtFurtherInformation.setText("Place Dispensary");
            jtxtStorageAdvice.setText("Less than 20%");
            jtxtDrivingUsingMachines.setText("No");
            jtxtHowtoUseMedication.setText("Use water, No Alcohol");
            jtxtPatientID.setText("P9589454");
            jtxtDoctorNHSNo.setText("646564");
            
        }
        
          else if (jcmbNameTablets.getSelectedItem().equals("Co-codamol"))
        {
            jtxtRef.setText("COCO6758940");
            jtxtDose.setText("500");
            jtxtNumberTablets.setText("30");
            jtxtLot.setText("B770034");
            jtxtIssuedDate.setText("06/05/2018");
            jtxtExpDate.setText("04/12/2019");
            jtxtDailyDose.setText("2");

            jtxtPossibleSideEffects.setText("Dizziness");
            jtxtFurtherInformation.setText("Place Dispensary");
            jtxtStorageAdvice.setText("Less than 20%");
            jtxtDrivingUsingMachines.setText("No");
            jtxtHowtoUseMedication.setText("Use water, No Alcohol");
            jtxtPatientID.setText("P9589454");
            jtxtDoctorNHSNo.setText("646564");

        }

        else if (jcmbNameTablets.getSelectedItem().equals("Paracetamol"))
        {
            jtxtRef.setText("01729214");
            jtxtDose.setText("500");
            jtxtNumberTablets.setText("16");
            jtxtLot.setText("0204324");
            jtxtIssuedDate.setText("07/05/2018");
            jtxtExpDate.setText("04/05/2023");
            jtxtDailyDose.setText("2");

            jtxtPossibleSideEffects.setText("Feeling Sick");
            jtxtFurtherInformation.setText("Place Dispensary");
            jtxtStorageAdvice.setText("Less than 25%");
            jtxtDrivingUsingMachines.setText("No");
            jtxtHowtoUseMedication.setText("Use water, No Alcohol");
            jtxtPatientID.setText("P5562454");
            jtxtDoctorNHSNo.setText("875564");

        }

        else if (jcmbNameTablets.getSelectedItem().equals("Amlodipine"))
        {
            jtxtRef.setText("Am05875");
            jtxtDose.setText("5");
            jtxtNumberTablets.setText("28");
            jtxtLot.setText("8745475");
            jtxtIssuedDate.setText("06/05/2018");
            jtxtExpDate.setText("04/05/2020");
            jtxtDailyDose.setText("1");

            jtxtPossibleSideEffects.setText("Liver Disease");
            jtxtFurtherInformation.setText("Ability to drive may be affected");
            jtxtStorageAdvice.setText("No Special Storage");
            jtxtDrivingUsingMachines.setText("No");
            jtxtHowtoUseMedication.setText("Use water, No Alcohol");
            jtxtPatientID.setText("P9129454");
            jtxtDoctorNHSNo.setText("6346564");

        }

        else if (jcmbNameTablets.getSelectedItem().equals("Make a Selection"))
        {
            jtxtRef.setText("");
            jtxtDose.setText("");
            jtxtNumberTablets.setText("");
            jtxtLot.setText("");
            jtxtIssuedDate.setText("");
            jtxtExpDate.setText("");
            jtxtDailyDose.setText("");

            jtxtPossibleSideEffects.setText("");
            jtxtFurtherInformation.setText("");
            jtxtStorageAdvice.setText("");
            jtxtAdministration.setText("");
            jtxtDrivingUsingMachines.setText("");
            jtxtHowtoUseMedication.setText("");
            jtxtPatientID.setText("");
            jtxtPatientName.setText("");
            jtxtDoctorNHSNo.setText("");
            jtxtAddress.setText("");
            jtxtPrescription.setText("");

        }
        

    }//GEN-LAST:event_jcmbNameTabletsActionPerformed

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed

       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.addRow(new Object[]{jcmbNameTablets.getSelectedItem().toString(),
       jtxtRef.getText(),jtxtDose.getText(),jtxtNumberTablets.getText(),jtxtLot.getText(),
       jtxtIssuedDate.getText(),jtxtExpDate.getText(), jtxtDailyDose.getText(),
       jtxtPossibleSideEffects.getText(),jtxtFurtherInformation.getText(), jtxtStorageAdvice.getText(),
       jtxtAdministration.getText(),jtxtDrivingUsingMachines.getText(),
       jtxtHowtoUseMedication.getText(),jtxtPatientID.getText(),jtxtDoctorNHSNo.getText(),
       jtxtPatientName.getText(),jtxtAdministration.getText(),jtxtAddress.getText(),});
    }//GEN-LAST:event_jbtnUpdateActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       if (jTable1.getSelectedRow() ==-1){
         if (jTable1.getRowCount() ==0){
             
             JOptionPane.showMessageDialog(null, "No data to delete","Hospital Management Systems",
                     JOptionPane.OK_OPTION  );
         }else{
             JOptionPane.showMessageDialog(null, "Select a row to delete","Hospital Management Systems",
                     JOptionPane.OK_OPTION );
         }
       }else{
           model.removeRow(jTable1.getSelectedRow());
       }
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    private void jbtnDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDoctorActionPerformed
       Doctor iLogin = new Doctor();
        iLogin.setVisible(true);
    }//GEN-LAST:event_jbtnDoctorActionPerformed

    private void jbtnPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPaymentActionPerformed
            jtxtRef.setText("");
            jtxtDose.setText("");
            jtxtNumberTablets.setText("");
            jtxtLot.setText("");
            jtxtIssuedDate.setText("");
            jtxtExpDate.setText("");
            jtxtDailyDose.setText("");

            jtxtPossibleSideEffects.setText("");
            jtxtFurtherInformation.setText("");
            jtxtStorageAdvice.setText("");
            jtxtAdministration.setText("");
            jtxtDrivingUsingMachines.setText("");
            jtxtHowtoUseMedication.setText("");
            jtxtPatientID.setText("");
            jtxtPatientName.setText("");
            jtxtDoctorNHSNo.setText("");
            jtxtAddress.setText("");
            jtxtPrescription.setText(""); 
            jcmbNameTablets.getModel().setSelectedItem("Make a Selection");
    }//GEN-LAST:event_jbtnPaymentActionPerformed

    private void jbtnPharmacyOfficeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPharmacyOfficeActionPerformed
        String Qty1 = (jtxtRef.getText());
        String Qty2 = (jtxtDose.getText());
        String Qty3 = (jtxtNumberTablets.getText());
        String Qty4 = (jtxtLot.getText());
        String Qty5 = (jtxtDailyDose.getText());
        String Qty6 = (jtxtPossibleSideEffects.getText());
        String Qty7 = (jtxtFurtherInformation.getText());
        String Qty8 = (jtxtHowtoUseMedication.getText());
        String Qty9 = (jtxtPatientID.getText());        
        String Qty10 = (jtxtPatientName.getText());        
        String Qty11 = (jtxtAdministration.getText());
        String Qty12 = (jtxtAddress.getText());
        String Qty13 = "";
        
         if (jcmbNameTablets.getSelectedItem().equals("Ibuprofen"))
        {
            Qty13 = "Ibuprofen";
        } 
         
         else  if (jcmbNameTablets.getSelectedItem().equals("Co-codamol"))
        {
            Qty13 = "Co-codamol";
        } 
         
          else  if (jcmbNameTablets.getSelectedItem().equals("Paracetamol"))
        {
            Qty13 = "Paracetamol";
        } 
         
          else  if (jcmbNameTablets.getSelectedItem().equals("Amlodipine"))
        {
            Qty13 = "Amlodipine";
        } 

        
        jtxtPrescription.setText("");
        jtxtPrescription.append("\t\n\tHospital Management Systems\n"
        +"\nPatient Name:\t\t" + Qty10
        +"\nDate of Birth:\t\t" + Qty11
        +"\nPatient Address:\t" + Qty12
        + "\nPrescription:\t\t" + Qty13
        + "\n\nReference No:\t\t" + Qty1 
        +  "\nDose (mg):\t\t"+ Qty2 
        +"\nNumber of Tablets:\t" + Qty3 
        + "\nLOT:\t\t" + Qty4 
        +  "\nDaily Dose:\t\t"+ Qty5 
        +"\nPossible Side Effects:\t" + Qty6 
        + "\nFurther Information:\t" + Qty7 
        +  "\nHow to Use Medication:\t"+ Qty8 
        +"\nPatient ID:\t\t" + Qty9 
        +"\n\n\tPatient Instruction we have introduced a \n\tfree text confirmation\n\t"
                     + "TEXT REMINDERS FOR APPOINTMENT" );
        
        
    }//GEN-LAST:event_jbtnPharmacyOfficeActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
        try{
            jtxtPrescription.print();
        }catch (PrinterException ex){
            Logger.getLogger(Hospital.class.getName()).log(Level.SEVERE, null,ex);
        }
    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        frame =new JFrame();
        if (JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit", "Hospital Management Systems",
              JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPatientActionPerformed
       Patient iLogin = new Patient();
        iLogin.setVisible(true);
    }//GEN-LAST:event_jbtnPatientActionPerformed

    private void jbtnGPAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGPAppointmentActionPerformed
    GPAppointment iLogin = new GPAppointment();
    iLogin.setVisible(true);      
    }//GEN-LAST:event_jbtnGPAppointmentActionPerformed

    private void jbtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoginActionPerformed
        Login iLogin = new Login();
        iLogin.setVisible(true);
    }//GEN-LAST:event_jbtnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hospital().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnDoctor;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnGPAppointment;
    private javax.swing.JButton jbtnLogin;
    private javax.swing.JButton jbtnPatient;
    private javax.swing.JButton jbtnPayment;
    private javax.swing.JButton jbtnPharmacyOffice;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JComboBox<String> jcmbNameTablets;
    private javax.swing.JTextField jtxtAddress;
    private javax.swing.JTextField jtxtAdministration;
    private javax.swing.JTextField jtxtDailyDose;
    private javax.swing.JTextField jtxtDoctorNHSNo;
    private javax.swing.JTextField jtxtDose;
    private javax.swing.JTextField jtxtDrivingUsingMachines;
    private javax.swing.JTextField jtxtExpDate;
    private javax.swing.JTextField jtxtFurtherInformation;
    private javax.swing.JTextField jtxtHowtoUseMedication;
    private javax.swing.JTextField jtxtIssuedDate;
    private javax.swing.JTextField jtxtLot;
    private javax.swing.JTextField jtxtNumberTablets;
    private javax.swing.JTextField jtxtPatientID;
    private javax.swing.JTextField jtxtPatientName;
    private javax.swing.JTextField jtxtPossibleSideEffects;
    private javax.swing.JTextArea jtxtPrescription;
    private javax.swing.JTextField jtxtRef;
    private javax.swing.JTextField jtxtStorageAdvice;
    // End of variables declaration//GEN-END:variables
}
