/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Doctor;

import javax.swing.JFrame;
import Login.Login;
//import Pharmacy.Pharmacy;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author paul.oamen
 */
public class Doctor extends javax.swing.JFrame {

     private JFrame frame;
    /**
     * Creates new form Doctor
     */
    public Doctor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtFirstname = new javax.swing.JTextField();
        jtxtSurname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtMedicalCentreName = new javax.swing.JTextField();
        jtxtPatient_ID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtAddressofCentre = new javax.swing.JTextField();
        jtxtPostCode = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtxtMedicalCentreRef = new javax.swing.JTextField();
        jtxtOfficePhoneNo1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtxtOfficePhoneNo2 = new javax.swing.JTextField();
        jtxtFaxNo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtxtEmailAddress = new javax.swing.JTextField();
        jtxtPatientNHSNumber = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jtxtEMISNumber = new javax.swing.JTextField();
        jtxtDoctorNHSNo = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jbtnPharmacyOffice = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jbtnUpdate = new javax.swing.JButton();
        jbtnPharmacy = new javax.swing.JButton();
        jbtnGPAppointment = new javax.swing.JButton();
        jbtnPatient = new javax.swing.JButton();
        jbtnPayment = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnLogin = new javax.swing.JButton();
        jtxtGPAppointment = new javax.swing.JTextField();
        jcmbNameTablets = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        setPreferredSize(new java.awt.Dimension(1400, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("GP Appointment Ref");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 400, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Doctor's Ref No");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Firstname");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jtxtFirstname.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(jtxtFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 290, -1));

        jtxtSurname.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(jtxtSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 290, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Surname");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Medical Centre Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jtxtMedicalCentreName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(jtxtMedicalCentreName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 290, -1));

        jtxtPatient_ID.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(jtxtPatient_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 290, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("EMIS Number");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 350, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Address of Centre");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        jtxtAddressofCentre.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(jtxtAddressofCentre, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 290, -1));

        jtxtPostCode.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(jtxtPostCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 290, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Post Code");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Medical Centre Ref");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, -1, -1));

        jtxtMedicalCentreRef.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(jtxtMedicalCentreRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 20, 300, -1));

        jtxtOfficePhoneNo1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(jtxtOfficePhoneNo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 80, 300, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Office Phone No 1");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("Office Phone No 2");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, -1, -1));

        jtxtOfficePhoneNo2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(jtxtOfficePhoneNo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 130, 300, -1));

        jtxtFaxNo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(jtxtFaxNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 190, 300, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("Fax No");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 190, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("Email Address");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, -1, -1));

        jtxtEmailAddress.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(jtxtEmailAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 240, 300, -1));

        jtxtPatientNHSNumber.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(jtxtPatientNHSNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 300, 300, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setText("Patient NHS Number");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setText("Patient ID");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jtxtEMISNumber.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(jtxtEMISNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 350, 300, -1));

        jtxtDoctorNHSNo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(jtxtDoctorNHSNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 290, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setText("Doctors NHS No");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Doctor's Ref No", "Doctor NHS No", "Firstname", "Surname", "Medical Centre Name", "Patirnt ID", "Address of Center", "Post Code", "Medical Centre Ref", "Office Phone No 1", "Office Phone No 2", "Fax No", "Email Address", "Patient NHS Number", "EMIS Number", "GP Appointment Ref"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 1300, 260));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnPharmacyOffice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnPharmacyOffice.setText("Pharmacy Office");
        jbtnPharmacyOffice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPharmacyOfficeActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnPharmacyOffice, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, 150, 30));

        jbtnDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnDelete.setText("Delete");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 140, 30));

        jbtnUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnUpdate.setText("Update");
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 30));

        jbtnPharmacy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnPharmacy.setText("Pharmacy");
        jbtnPharmacy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPharmacyActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnPharmacy, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 140, 30));

        jbtnGPAppointment.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnGPAppointment.setText("GP Appointment");
        jPanel1.add(jbtnGPAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 150, 30));

        jbtnPatient.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnPatient.setText("Patient");
        jPanel1.add(jbtnPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 140, 30));

        jbtnPayment.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnPayment.setText("Payment");
        jPanel1.add(jbtnPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, 140, 30));

        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 10, 140, 30));

        jbtnLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnLogin.setText("Login");
        jbtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 10, 140, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 1300, 50));

        jtxtGPAppointment.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(jtxtGPAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 400, 300, -1));

        jcmbNameTablets.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jcmbNameTablets.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Doctor's Ref", "PO05984", "JK956858", "QM90595", "QE29845" }));
        jcmbNameTablets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbNameTabletsActionPerformed(evt);
            }
        });
        getContentPane().add(jcmbNameTablets, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 290, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnPharmacyOfficeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPharmacyOfficeActionPerformed

    }//GEN-LAST:event_jbtnPharmacyOfficeActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if(jTable1.getSelectedRow()==-1){
            if(jTable1.getRowCount()==0){

                JOptionPane.showMessageDialog(null, "No data to delete ",
                    "Pharmacy Management System",JOptionPane.OK_OPTION);
            }else{

                JOptionPane.showMessageDialog(null, "Select a row to delete ",
                    "Pharmacy Management System",JOptionPane.OK_OPTION);
            }
        }else{
            model.removeRow(jTable1.getSelectedRow());
        }
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        model.addRow(new Object[]{jcmbNameTablets.getSelectedItem().toString(),
            jtxtDoctorNHSNo.getText(),jtxtFirstname.getText(),jtxtSurname.getText(),jtxtMedicalCentreName.getText(),
            jtxtPatient_ID.getText(),jtxtAddressofCentre.getText(), jtxtPostCode.getText(),
            jtxtMedicalCentreRef.getText(),jtxtOfficePhoneNo1.getText(), jtxtOfficePhoneNo2.getText(),
            jtxtFaxNo.getText(),jtxtEmailAddress.getText(),
            jtxtPatientNHSNumber.getText(),
            jtxtEMISNumber.getText(),jtxtGPAppointment.getText(),});

    }//GEN-LAST:event_jbtnUpdateActionPerformed

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit","Pharmacy Management Systems",
            JOptionPane.YES_NO_OPTION ) ==JOptionPane.YES_NO_OPTION){
        System.exit(0);
        }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoginActionPerformed
        Login iLogin = new Login();
        iLogin.setVisible(true);
    }//GEN-LAST:event_jbtnLoginActionPerformed

    private void jbtnPharmacyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPharmacyActionPerformed
        //Pharmacy iPharmacy = new Pharmacy();
      //  iPharmacy.setVisible(true);
    }//GEN-LAST:event_jbtnPharmacyActionPerformed

    private void jcmbNameTabletsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbNameTabletsActionPerformed
        if (jcmbNameTablets.getSelectedItem().equals("PO05984"))
        {              
            
            jtxtDoctorNHSNo.setText("Dr857855");
            jtxtFirstname.setText("Paul");
            jtxtSurname.setText("Oamen");
            jtxtMedicalCentreName.setText("Vale Medical Centre");
            jtxtPatient_ID.setText("46747677");
            jtxtAddressofCentre.setText("10 Roadwork Lane");
            jtxtPostCode.setText("HG748");

            jtxtMedicalCentreRef.setText("MCR68945");
            jtxtOfficePhoneNo1.setText("0202356798555");
            jtxtOfficePhoneNo2.setText("0202356798556");
            jtxtFaxNo.setText("0202356798557");
            jtxtEmailAddress.setText("vale.med@gmail.com");
            jtxtPatientNHSNumber.setText("7648749830");
            jtxtEMISNumber.setText("Y6589454");
            jtxtGPAppointment.setText("Yes");

        }
      else if (jcmbNameTablets.getSelectedItem().equals("JK956858"))
        {  
           
            jtxtDoctorNHSNo.setText("Dr894843");
            jtxtFirstname.setText("Jackson");
            jtxtSurname.setText("Kings");
            jtxtMedicalCentreName.setText("Vale Medical Centre");
            jtxtPatient_ID.setText("3457677");
            jtxtAddressofCentre.setText("10 Roadwork Lane");
            jtxtPostCode.setText("HG748");

            jtxtMedicalCentreRef.setText("MCR68945");
            jtxtOfficePhoneNo1.setText("0202356798553");
            jtxtOfficePhoneNo2.setText("0202356798554");
            jtxtFaxNo.setText("0202356798552");
            jtxtEmailAddress.setText("Kings.med@gmail.com");
            jtxtPatientNHSNumber.setText("76434555");
            jtxtEMISNumber.setText("Y65895554");
            jtxtGPAppointment.setText("Yes");

        }
        
      else if (jcmbNameTablets.getSelectedItem().equals("QM90595"))
        {   
            jtxtDoctorNHSNo.setText("DRNHs8573");
            jtxtFirstname.setText("Ewu");
            jtxtSurname.setText("Eko");
            jtxtMedicalCentreName.setText("Vale Medical Centre");
            jtxtPatient_ID.setText("343456");
            jtxtAddressofCentre.setText("10 Roadwork Lane");
            jtxtPostCode.setText("HG748");

            jtxtMedicalCentreRef.setText("MCR68945");
            jtxtOfficePhoneNo1.setText("0202356794547");
            jtxtOfficePhoneNo2.setText("0202356798521");
            jtxtFaxNo.setText("02023567912387");
            jtxtEmailAddress.setText("EwuEko.med@gmail.com");
            jtxtPatientNHSNumber.setText("78521255");
            jtxtEMISNumber.setText("Y07574554");
            jtxtGPAppointment.setText("Yes");

        }
        
      else if (jcmbNameTablets.getSelectedItem().equals("QE29845"))
        {   
            jtxtDoctorNHSNo.setText("DrNHS968");
            jtxtFirstname.setText("Johnny");
            jtxtSurname.setText("Josuah");
            jtxtMedicalCentreName.setText("Vale Medical Centre");
            jtxtPatient_ID.setText("34290887");
            jtxtAddressofCentre.setText("10 Roadwork Lane");
            jtxtPostCode.setText("HG748");

            jtxtMedicalCentreRef.setText("MCR68945");
            jtxtOfficePhoneNo1.setText("020245534553");
            jtxtOfficePhoneNo2.setText("02023455554");
            jtxtFaxNo.setText("020235234552");
            jtxtEmailAddress.setText("Johnny.med@gmail.com");
            jtxtPatientNHSNumber.setText("7855S555");
            jtxtEMISNumber.setText("54655554");
            jtxtGPAppointment.setText("Yes");
        }
        
        else if (jcmbNameTablets.getSelectedItem().equals("Select Doctor's Ref"))
        { 
            jtxtDoctorNHSNo.setText("");
            jtxtFirstname.setText("");
            jtxtSurname.setText("");
            jtxtMedicalCentreName.setText("");
            jtxtPatient_ID.setText("");
            jtxtAddressofCentre.setText("");
            jtxtPostCode.setText("");

            jtxtMedicalCentreRef.setText("");
            jtxtOfficePhoneNo1.setText("");
            jtxtOfficePhoneNo2.setText("");
            jtxtFaxNo.setText("");
            jtxtEmailAddress.setText("");
            jtxtPatientNHSNumber.setText("");
            jtxtEMISNumber.setText("");
            jtxtGPAppointment.setText("");
}
        
    }//GEN-LAST:event_jcmbNameTabletsActionPerformed

    /*
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnGPAppointment;
    private javax.swing.JButton jbtnLogin;
    private javax.swing.JButton jbtnPatient;
    private javax.swing.JButton jbtnPayment;
    private javax.swing.JButton jbtnPharmacy;
    private javax.swing.JButton jbtnPharmacyOffice;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JComboBox<String> jcmbNameTablets;
    private javax.swing.JTextField jtxtAddressofCentre;
    private javax.swing.JTextField jtxtDoctorNHSNo;
    private javax.swing.JTextField jtxtEMISNumber;
    private javax.swing.JTextField jtxtEmailAddress;
    private javax.swing.JTextField jtxtFaxNo;
    private javax.swing.JTextField jtxtFirstname;
    private javax.swing.JTextField jtxtGPAppointment;
    private javax.swing.JTextField jtxtMedicalCentreName;
    private javax.swing.JTextField jtxtMedicalCentreRef;
    private javax.swing.JTextField jtxtOfficePhoneNo1;
    private javax.swing.JTextField jtxtOfficePhoneNo2;
    private javax.swing.JTextField jtxtPatientNHSNumber;
    private javax.swing.JTextField jtxtPatient_ID;
    private javax.swing.JTextField jtxtPostCode;
    private javax.swing.JTextField jtxtSurname;
    // End of variables declaration//GEN-END:variables
}
