/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Patient;

/**
 *
 * @author paul.oamen
 */
public class Patient extends javax.swing.JFrame {

    /**
     * Creates new form Patient
     */
    public Patient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel22 = new javax.swing.JLabel();
        jtxtRef = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jtxtDose = new javax.swing.JTextField();
        jtxtNumberTablets = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtLot = new javax.swing.JTextField();
        jtxtIssuedDate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtExpDate = new javax.swing.JTextField();
        jtxtDailyDose = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtxtPossibleSideEffects = new javax.swing.JTextField();
        jtxtFurtherInformation = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtxtStorageAdvice = new javax.swing.JTextField();
        jtxtAdministration = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtxtDrivingUsingMachines = new javax.swing.JTextField();
        jtxtHowtoUseMedication = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jtxtPatientID = new javax.swing.JTextField();
        jtxtDoctorNHSNo = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jtxtPatientName = new javax.swing.JTextField();
        jtxtAddress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtxtRef1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1400, 800));
        setPreferredSize(new java.awt.Dimension(1400, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("Reference No.");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));

        jtxtRef.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 210, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setText("Name of Tablets:");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setText("Dose (mg):");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, -1, -1));

        jtxtDose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 210, -1));

        jtxtNumberTablets.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtNumberTablets, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 210, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Number of Tablets:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, -1, -1));

        jtxtLot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtLot, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 210, -1));

        jtxtIssuedDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtIssuedDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 210, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Issued Date:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Exp Date:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, -1, -1));

        jtxtExpDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtExpDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, 210, -1));

        jtxtDailyDose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtDailyDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, 210, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Daily Dose:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, -1, -1));

        jtxtPossibleSideEffects.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtPossibleSideEffects, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 480, 210, -1));

        jtxtFurtherInformation.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtFurtherInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 160, 210, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Further Information:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 160, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Storage Advice:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, -1, -1));

        jtxtStorageAdvice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtStorageAdvice, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 200, 210, -1));

        jtxtAdministration.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtAdministration, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 440, 210, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Date of Birth:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Driving and Using Machines:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, -1, -1));

        jtxtDrivingUsingMachines.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtDrivingUsingMachines, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 240, 210, -1));

        jtxtHowtoUseMedication.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtHowtoUseMedication, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 280, 210, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("How to Use Medication:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 280, -1, -1));

        jtxtPatientID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtPatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 320, 210, -1));

        jtxtDoctorNHSNo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtDoctorNHSNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 360, 210, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("NHS Number:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 360, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Possible Side Effects:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Patient ID:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Patient Address:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 490, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("Patient Name:");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 400, -1, -1));

        jtxtPatientName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 400, 210, -1));

        jtxtAddress.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 480, 210, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("LOT:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Patient Prescription");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 930, 60));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel1.setText("Hospital Management Systems");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 530, -1, -1));

        jtxtRef1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jtxtRef1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 210, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Patient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jtxtAddress;
    private javax.swing.JTextField jtxtAdministration;
    private javax.swing.JTextField jtxtDailyDose;
    private javax.swing.JTextField jtxtDoctorNHSNo;
    private javax.swing.JTextField jtxtDose;
    private javax.swing.JTextField jtxtDrivingUsingMachines;
    private javax.swing.JTextField jtxtExpDate;
    private javax.swing.JTextField jtxtFurtherInformation;
    private javax.swing.JTextField jtxtHowtoUseMedication;
    private javax.swing.JTextField jtxtIssuedDate;
    private javax.swing.JTextField jtxtLot;
    private javax.swing.JTextField jtxtNumberTablets;
    private javax.swing.JTextField jtxtPatientID;
    private javax.swing.JTextField jtxtPatientName;
    private javax.swing.JTextField jtxtPossibleSideEffects;
    private javax.swing.JTextField jtxtRef;
    private javax.swing.JTextField jtxtRef1;
    private javax.swing.JTextField jtxtStorageAdvice;
    // End of variables declaration//GEN-END:variables
}
